services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/run.osm.pbf && 
      osrm-partition /data/run.osrm && 
      osrm-customize /data/run.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/run.osrm
      "